title: SLAM Handbook Python
author: Ryohei Sasaki
logo: ""

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/rsasaki0109/slam-handbook-python
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
  config:
    html_theme_options:
      navigation_with_keys: false
